name: addblog

on:
  push:
    paths:
    - '_data/feeds/planetid'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.5' 
      - uses: py-actions/py-dependency-install@v2   
      - shell: bash
        run: export relative=_data/feeds/planetid/ && export config=$(ls -t _data/feeds/planetid | head -1) && export ini=planetid.ini && python addfeed.py
      - name: Deploy Changes
        run: |
          git remote add gh-token "https://github.com/identosphere/planetid-reboot.git"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git commit -a -m "add organization"
          git push gh-token master
