name: addorg

on:
  push:
    paths:
    - '_data/feeds/orgsfeed'
    - 'addfeed.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.5' 
      - uses: py-actions/py-dependency-install@v2   
      - shell: bash
        run: export config=$(ls -t _data/feeds/orgsfeed | head -1) && export ini=organizatinos.ini && python addfeed.py
