# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Build Media

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '20 */5 * * *'
  push:
    paths:
    - 'media.ini'
    - .github/workflows/media.yml

jobs:
  updatefeeds:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: gem install pluto && gem install nokogiri && gem install sanitize
    - name: build media
      run: pluto --verbose b media.ini -t media -o docs/media
    - name: Deploy Files
      run: |
        git remote add gh-token "https://github.com/identosphere/identity-blogcatcher.git"
        git config user.name "github-actions[bot]" # I use the GitHub Actions bot here.
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git pull
        git add .
        git commit -a -m "update media"
        git push gh-token master
